---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
  - name: Add apt-key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com

  - name: Add repo
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: Install MongoDB
    apt:
      name: mongodb-org
      state: latest
      update_cache: yes

  - name: Enable MongoDB
    systemd:
      name: mongod
      state: started
      enabled: yes
