---
- name: Install Ruby
  hosts: all
  become: true
  tasks:
    - name: Install Ruby
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
          - ruby-full
          - ruby-bundler
          - build-essential
