---
- name: Configure hosts and deploy app
  hosts: all
  vars:
  #  mongo_bind_ip: "{{ ansible_ens4.ipv4.address }}"
     mongo_bind_ip: 0.0.0.0
     db_host: 10.164.0.2
  tasks:
  - name: Change mongo conf
    become: true
    template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
    tags: db-tag
    notify: restart mongodb

  - name: add puma unit file
    become: true
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
    tags: app-tag
    notify: reload puma
  - name: Change mongo conf
    become: true
    template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
    tags: app-tag
  - name: enable puma
    become: true
    systemd:
      name: puma
      enabled: true
      state: started
    tags: app-tag

  - name: Fetch latest app version
    git:
      repo: 'https://github.com/Otus-DevOps-2017-11/reddit.git'
      dest: /home/appuser/reddit
      version: monolith
    tags: deploy-tag
    notify: restart puma
  - name: Bundle install
    bundler:
      state: present
      chdir: /home/appuser/reddit
    tags: deploy-tag


  handlers:
  - name: restart mongodb
    become: true
    service: name=mongod state=restarted

  - name: reload puma
    become: true
    service: name=puma state=restarted

  - name: restart puma
    become: true
    service: name=puma state=restarted